const wordList=[
    {word:"Shimmer" ,
    hint:"To shine with a flickering, wavering light."},
    {word:"Glisten",
    hint:"To sparkle or shine with a soft, radiant light."},
    {word:"Resilient",
    hint:"Capable of recovering quickly from difficulties."},
    {word:"Enigma",
    hint:"A mysterious or puzzling person, thing, or situation."},
    {word:"Paradox",
    hint:"A statement or situation that appears contradictory but may reveal a truth."},
    {word:"Aesthetic",
    hint:"Concerned with beauty and artistic appreciation."},
    {word:"Candid",
    hint:"Open, honest, and straightforward."},
    {word:"Deft",
    hint:"Skillful and quick in one's movements or actions."},
    {word:"Lethargic",
    hint:"Sluggish and lacking energy or enthusiasm."},
    {word:"Melancholy",
    hint:"A feeling of deep sadness or sorrow."},
    {word:"Amiable",
    hint:"Having a friendly and pleasant manner."},
    {word:"Prolific",
    hint:"Producing many works, results, or offspring."},
    {word:"Viable",
    hint:"Capable of working successfully; feasible."},
    {word:"Cognizant",
    hint:"Fully aware or knowledgeable about something."},
    {word:"Benevolent",
    hint:"Kind and generous in intention or purpose."},
    {word:"Divergent",
    hint:"Tending to be different or develop in different directions."},
    {word:"Nuance",
    hint:"A subtle difference or distinction in meaning or expression."},
    {word:"Inherent",
    hint:" Existing as a natural and essential quality."},
    {word:"Esoteric",
    hint:"Intended for or understood by a small, specific group."},
    {word:"Apathy",
    hint:"Lack of interest, enthusiasm, or concern."},
    {word:"Eloquent",
    hint:"Fluent and persuasive in speech or writing."},
    {word:"Resonate",
    hint:" Evoke a strong feeling or connection."},
    {word:"Enigma",
    hint:"A puzzling or mysterious person or situation."},
    {word:"Pragmatic",
    hint:"Dealing with things in a practical and realistic way."},
    {word:"Vehement",
    hint:"Showing strong and intense feeling or passion."},
    {word:"Tenacious",
    hint:"Persistent and determined in pursuit of a goal."},
    {word:"Pensive",
    hint:"Deeply thoughtful, often with a hint of sadness."},
    {word:"Fervent",
    hint:"Displaying intense passion or enthusiasm."},
    {word:"Euphoria",
    hint:"A state of intense happiness and excitement."},
    {word:"Alacrity",
    hint:"Brisk and cheerful readiness to do something."},
    {word:"Disparate ",
    hint:"Distinctly different in nature, kind, or quality."},
    {word:"Aplomb",
    hint:"Self-confidence and composure, especially in challenging situations."},
    {word:"Malaise",
    hint:"A general feeling of discomfort, illness, or unease."},
    {word:"Acumen",
    hint:"The ability to make good judgments and quick decisions."},
    {word:"Pristine",
    hint:"In its original condition; unspoiled or untouched."}
  
]
