# Generated by Django 4.1 on 2022-09-04 05:44

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_ML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Backend_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Data_visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Devops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Frontend_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_app_devlopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Programming_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Static_site_gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='add_ons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('display visitors count badge', 'display visitors count badge'), ('display top skills', 'display top skills'), ('display github profile stats card', 'display github profile stats card')], max_length=300),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='behance',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='buy_me_coffee',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='codechef',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='codepen',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='codesandbox',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='dev',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='discord',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='dribble',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='facebook',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='gfg',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='github',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='hackerank',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='hackerearth',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='hashnode',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='instagram',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='kaggle',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='leetcode',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='linkedin',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='medium',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='project1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='project1_link',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='project2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='project2_link',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='project3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='project3_link',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='project4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='project4_link',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='project5',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='project5_link',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='resume_link',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='rss',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='topcoder',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='twitter',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='youtube',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='about_me',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.RemoveField(
            model_name='personal_readme',
            name='system',
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='aI_ML',
            field=models.ManyToManyField(blank=True, to='personal_readme.ai_ml'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='automation',
            field=models.ManyToManyField(blank=True, to='personal_readme.automation'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='bASS',
            field=models.ManyToManyField(blank=True, to='personal_readme.bass'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='backend_language',
            field=models.ManyToManyField(blank=True, to='personal_readme.backend_language'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='blockchain',
            field=models.ManyToManyField(blank=True, to='personal_readme.blockchain'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='data_visualization',
            field=models.ManyToManyField(blank=True, to='personal_readme.data_visualization'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='database',
            field=models.ManyToManyField(blank=True, to='personal_readme.database'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='devops',
            field=models.ManyToManyField(blank=True, to='personal_readme.devops'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='framework',
            field=models.ManyToManyField(blank=True, to='personal_readme.framework'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='frontend_language',
            field=models.ManyToManyField(blank=True, to='personal_readme.frontend_language'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='game_engine',
            field=models.ManyToManyField(blank=True, to='personal_readme.game_engine'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='mobile_app_devlopment',
            field=models.ManyToManyField(blank=True, to='personal_readme.mobile_app_devlopment'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='others',
            field=models.ManyToManyField(blank=True, to='personal_readme.others'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='programming_language',
            field=models.ManyToManyField(blank=True, to='personal_readme.programming_language'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='software',
            field=models.ManyToManyField(blank=True, to='personal_readme.software'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='static_site_gen',
            field=models.ManyToManyField(blank=True, to='personal_readme.static_site_gen'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='testing',
            field=models.ManyToManyField(blank=True, to='personal_readme.testing'),
        ),
        migrations.AddField(
            model_name='personal_readme',
            name='system',
            field=models.ManyToManyField(blank=True, to='personal_readme.systemchoice'),
        ),
    ]
