# Generated by Django 4.1 on 2022-09-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0002_ai_ml_automation_backend_language_bass_blockchain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_readme',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
