# Generated by Django 4.1 on 2022-09-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0003_personal_readme_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_readme',
            name='project1',
        ),
    ]
