# Generated by Django 4.1 on 2022-09-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0004_remove_personal_readme_project1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_readme',
            name='codechef',
        ),
        migrations.RemoveField(
            model_name='personal_readme',
            name='codesandbox',
        ),
        migrations.RemoveField(
            model_name='personal_readme',
            name='gfg',
        ),
    ]
