# Generated by Django 4.1 on 2022-09-12 14:40

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0005_remove_personal_readme_codechef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_readme',
            name='patreon',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='((http|https)://)(www.)?[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)')]),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='add_ons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('display visitors count badge', 'display visitors count badge'), ('display top skills', 'display top skills'), ('display github profile stats card', 'display github profile stats card')], max_length=500),
        ),
    ]
