# Generated by Django 4.1 on 2022-09-13 15:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0006_personal_readme_patreon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_readme',
            name='aI_ML',
            field=models.ManyToManyField(blank=True, related_name='ai_ml', to='personal_readme.ai_ml'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='add_ons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Display visitors count badge', 'Display visitors count badge'), ('Display github trophy', 'Display github trophy'), ('Display top skills', 'Display top skills'), ('Display github profile stats card', 'Display github profile stats card'), ('Display github streak stats', 'Display github streak stats')], max_length=500),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='automation',
            field=models.ManyToManyField(blank=True, related_name='automation', to='personal_readme.automation'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='bASS',
            field=models.ManyToManyField(blank=True, related_name='bass', to='personal_readme.bass'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='backend_language',
            field=models.ManyToManyField(blank=True, related_name='backend_language', to='personal_readme.backend_language'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='blockchain',
            field=models.ManyToManyField(blank=True, related_name='blockchain', to='personal_readme.blockchain'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='data_visualization',
            field=models.ManyToManyField(blank=True, related_name='data_visualiztion', to='personal_readme.data_visualization'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='database',
            field=models.ManyToManyField(blank=True, related_name='database', to='personal_readme.database'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='devops',
            field=models.ManyToManyField(blank=True, related_name='devops', to='personal_readme.devops'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='framework',
            field=models.ManyToManyField(blank=True, related_name='framework', to='personal_readme.framework'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='frontend_language',
            field=models.ManyToManyField(blank=True, related_name='frontend_language', to='personal_readme.frontend_language'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='game_engine',
            field=models.ManyToManyField(blank=True, related_name='game_engine', to='personal_readme.game_engine'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='github',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='mobile_app_devlopment',
            field=models.ManyToManyField(blank=True, related_name='mobile_app_devlopment', to='personal_readme.mobile_app_devlopment'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='others',
            field=models.ManyToManyField(blank=True, related_name='others', to='personal_readme.others'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='programming_language',
            field=models.ManyToManyField(blank=True, related_name='programming_language', to='personal_readme.programming_language'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='software',
            field=models.ManyToManyField(blank=True, related_name='software', to='personal_readme.software'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='static_site_gen',
            field=models.ManyToManyField(blank=True, related_name='static_site_gen', to='personal_readme.static_site_gen'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='system',
            field=models.ManyToManyField(blank=True, related_name='system', to='personal_readme.systemchoice'),
        ),
        migrations.AlterField(
            model_name='personal_readme',
            name='testing',
            field=models.ManyToManyField(blank=True, related_name='testing', to='personal_readme.testing'),
        ),
    ]
