# Generated by Django 4.1 on 2022-09-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0009_alter_personal_readme_add_ons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_readme',
            old_name='add_ons',
            new_name='addon',
        ),
    ]
