# Generated by Django 4.1 on 2022-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0012_remove_personal_readme_addon_personal_readme_add_ons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_readme',
            name='add_ons',
            field=models.CharField(blank=True, choices=[('first', 'Display visitors count badge'), ('second', 'Display github trophy'), ('third', 'Display top skills'), ('fourth', 'Display github profile stats card'), ('fifth', 'Display github streak stats')], default=None, max_length=500),
        ),
    ]
