# Generated by Django 4.1 on 2022-09-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0017_alter_personal_readme_add_ons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_readme',
            name='add_ons',
            field=models.CharField(blank=True, choices=[(1, 'Display visitors count badge'), (2, 'Display github trophy'), (3, 'Display top skills'), (4, 'Display github profile stats card'), (5, 'Display github streak stats')], max_length=500),
        ),
    ]
