# Generated by Django 4.1 on 2022-09-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0021_personal_readme_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal_readme',
            options={'get_latest_by': ['create_date']},
        ),
    ]
