# Generated by Django 4.1 on 2022-09-17 04:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0023_alter_personal_readme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_readme',
            name='add_ons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('one', 'Display visitors count badge'), ('two', 'Display github trophy'), ('three', 'Display top skills'), ('four', 'Display github profile stats card'), ('five', 'Display github streak stats')], max_length=500, null=True),
        ),
    ]
