# Generated by Django 4.1.1 on 2022-09-17 12:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0027_alter_personal_readme_add_ons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_readme',
            name='add_ons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Display visitors count badge', 'Display visitors count badge'), ('Display github trophy', 'Display github trophy'), ('Display top skills', 'Display top skills'), ('Display github profile stats card', 'Display github profile stats card'), ('Display github streak stats', 'Display github streak stats')], max_length=500, null=True),
        ),
    ]
