# Generated by Django 4.1.1 on 2022-09-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0032_add_on_remove_personal_readme_add_ons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_readme',
            name='add_ons',
            field=models.ManyToManyField(blank=True, related_name='add_ons', to='personal_readme.add_on'),
        ),
    ]
