# Generated by Django 4.1.1 on 2022-10-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_readme', '0034_alter_add_on_title_alter_ai_ml_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_readme',
            name='project1_link',
            field=models.URLField(blank=True),
        ),
    ]
