const jokes={
    0:"I was going to tell you a joke about boxing but I forgot the punch line.",
    1:"Why don't scientists trust atoms? Because they make up everything.",
    2:"I told my wife she was drawing her eyebrows too high. She looked surprised.",
    3:"Parallel lines have so much in common. It's a shame they'll never meet.",
    4:"I used to play piano by ear, but now I use my hands.",
    5:"Why did the scarecrow win an award? Because he was outstanding in his field.",
    6:"I'm reading a book on anti-gravity. It's impossible to put down.",
    7: "Why don't skeletons fight each other? They don't have the guts.",
    8: "I'm on a whiskey diet. I've lost three days already.",
    9: "Why did the bicycle fall over? Because it was two-tired.",
    10: "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
    11: "I'm reading a book about anti-gravity. It's uplifting.",
    12: "What do you call a fish with no eyes? Fsh.",
    13: "Why did the tomato turn red? Because it saw the salad dressing.",
    14: "I used to be a baker, but I couldn't make enough dough.",
    15: "Why don't scientists trust atoms? Because they make up everything.",
    16: "I'm friends with all electricians. We have such good current connections.",
    17: "I'm writing a book on reverse psychology. Please don't buy it.",
    18: "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    19: "What did one wall say to the other wall? 'I'll meet you at the corner.'",
    20: "I'm friends with all electricians. We have such good current connections.",
    21: "Why did the math book look sad? Because it had too many problems.",
    22: "How do you organize a space party? You planet.",
    23: "Why did the bicycle fall over? Because it was two-tired.",
    24: "Why don't skeletons fight each other? They don't have the guts.",
    25: "I'm reading a book on anti-gravity. It's impossible to put down.",
    26: "What do you call a fish with no eyes? Fsh.",
    27: "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
    28: "I'm on a whiskey diet. I've lost three days already.",
    29: "Why did the tomato turn red? Because it saw the salad dressing.",
    30: "I used to be a baker, but I couldn't make enough dough.",
    31: "What did one wall say to the other wall? 'I'll meet you at the corner.'",
    32: "I'm friends with all electricians. We have such good current connections.",
    33: "I'm writing a book on reverse psychology. Please don't buy it.",
    34: "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    35: "Why did the scarecrow win an award? Because he was outstanding in his field.",
    36: "I'm reading a book about anti-gravity. It's uplifting.",
    37: "What do you call a fake noodle? An impasta.",
    38: "Why don't scientists trust atoms? Because they make up everything.",
    39: "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    40:"What rock group has four men that don't sing? Mount Rushmore.",
    41:"When I was a kid, my mother told me I could be anyone I wanted to be. Turns out, identity theft is a crime.",
    42:"A guy goes to his doctor because he can see into the future. The doctor asks him,\"How long have you suffered from that condition?\" The guy tells him, \"Since next Monday.\"",
    43:"What do sprinters eat before a race? Nothing, they fast!",
    44:"What concert costs just 45 cents? 50 Cent featuring Nickelback!",
    45:"What do you call a mac 'n' cheese that gets all up in your face? Too close for comfort food!",
    46:"Why couldn't the bicycle stand up by itself? It was two tired!",
    47:"Did you hear about the restaurant on the moon? Great food, no atmosphere!",
    48:"How many apples grow on a tree? All of them!",
    49:"Did you hear the rumor about butter? Well, I'm not going to spread it!",
    50:"I like telling Dad jokes. Sometimes he laughs!",
    51:"To whoever stole my copy of Microsoft Office, I will find you. You have my Word!"
}

function joke() {
    const randomjoke=jokes[(Math.floor(Math.random()*52))];
    const joke=document.getElementById('joke');
    joke.innerHTML=randomjoke;
}